<?php
session_start();

// Security check: Must be logged in
if (!isset($_SESSION["loggedin"]) || $_SESSION["loggedin"] !== true) {
    $_SESSION['error'] = "You must be logged in to view this page.";
    header("location: ../auth/login.php");
    exit;
}

// Include database connection
require_once '../database/connection.php';

// Security check: Must be an admin or manager
$role_id = $_SESSION["role_id"] ?? null;
$allowed_roles = ['admin', 'manager'];

$user_role_name = '';
if ($role_id) {
    try {
        $sql = "SELECT name FROM roles WHERE id = :role_id";
        $stmt = $pdo->prepare($sql);
        $stmt->bindParam(':role_id', $role_id, PDO::PARAM_INT);
        $stmt->execute();
        if ($stmt->rowCount() == 1) {
            $user_role_name = strtolower($stmt->fetchColumn());
        }
    } catch (PDOException $e) {
        $_SESSION['error'] = "An unexpected error occurred.";
        header("location: ../auth/distribute.php");
        exit;
    }
}

if (!in_array($user_role_name, $allowed_roles)) {
    $_SESSION['error'] = "You do not have permission to view this page.";
    header("location: ../auth/distribute.php");
    exit;
}

// Fetch all reports with creator's username using a LEFT JOIN
$reports = $pdo->query("
    SELECT 
        r.id,
        r.total_category,
        r.total_product,
        r.total_available_product,
        r.total_broken_product,
        r.total_imported_product,
        r.total_exported_product,
        r.description,
        r.report_date,
        u.username as created_by_username
    FROM reports r
    LEFT JOIN users u ON r.created_by = u.id
    ORDER BY r.report_date DESC
")->fetchAll();

// Retrieve and clear messages from session
$message = $_SESSION['message'] ?? '';
$error = $_SESSION['error'] ?? '';
unset($_SESSION['message'], $_SESSION['error']);

$page_title = 'View System Reports';
include '../includes/header.php';
?>

<div class="container mt-5">
    <div class="row mb-3">
        <div class="col">
            <h2>System Reports</h2>
        </div>
        <div class="col text-right">
            <a href="../reports/add.php" class="btn btn-success">Generate New Report</a>
        </div>
    </div>

    <?php if ($message): ?><div class="alert alert-success"><?php echo htmlspecialchars($message); ?></div><?php endif; ?>
    <?php if ($error): ?><div class="alert alert-danger"><?php echo htmlspecialchars($error); ?></div><?php endif; ?>

    <div class="table-responsive">
        <table class="table table-bordered table-striped">
            <thead class="thead-dark">
                <tr>
                    <th>Date</th>
                    <th>Description</th>
                    <th>Total Categories</th>
                    <th>Total Products</th>
                    <th>Stock</th>
                    <th>Broken</th>
                    <th>Imported</th>
                    <th>Exported</th>
                    <th>Generated By</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($reports as $report): ?>
                <tr>
                    <td><?php echo htmlspecialchars(date('Y-m-d H:i', strtotime($report['report_date']))); ?></td>
                    <td><?php echo htmlspecialchars($report['description']); ?></td>
                    <td><?php echo htmlspecialchars($report['total_category']); ?></td>
                    <td><?php echo htmlspecialchars($report['total_product']); ?></td>
                    <td><?php echo htmlspecialchars($report['total_available_product']); ?></td>
                    <td><?php echo htmlspecialchars($report['total_broken_product']); ?></td>
                    <td><?php echo htmlspecialchars($report['total_imported_product']); ?></td>
                    <td><?php echo htmlspecialchars($report['total_exported_product']); ?></td>
                    <td><?php echo htmlspecialchars($report['created_by_username'] ?? 'N/A'); ?></td>
                    <td>
                        <a href="../reports/edit.php?id=<?php echo $report['id']; ?>" class="btn btn-primary btn-sm">Edit</a>
                        <a href="../reports/delete.php?id=<?php echo $report['id']; ?>" class="btn btn-danger btn-sm">Delete</a>
                    </td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>

<?php
include '../includes/footer.php';
?>